In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
mini_arr= arr[0:6]

In [6]:
mini_arr[:] = 0
mini_arr

array([0, 0, 0, 0, 0, 0])

In [8]:
#Esto es lo que no se queria, modificar el originial!
arr

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [10]:
#Lo que hace es hacer otro espacio en memoria, por lo que no ocupa el original!
arr_copy = arr.copy()
arr_copy

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])

In [11]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [12]:
arr

array([0, 0, 0, 0, 0, 0, 6, 7, 8, 9])