In [1]:
import numpy as np

In [4]:
arr = np.random.randint(1,10,(3,2))
#Con el shape se puede saber la dimension del array
arr.shape

(3, 2)

In [5]:
#Con el reshape, convierte un array a otro
arr.reshape(1,6)

array([[6, 7, 5, 4, 9, 8]])

In [7]:
#Los parametros son: a que y luego qué hacer
np.reshape(arr,(1,6))

array([[6, 7, 5, 4, 9, 8]])

In [9]:
#Con esto, se puede mostrar como lo ordena en C o en F
np.reshape(arr,(2,3),'C')

array([[6, 7, 5],
       [4, 9, 8]])

In [10]:
#Con esto, se puede mostrar como lo ordena en C o en F
np.reshape(arr,(2,3),'F')

array([[6, 9, 4],
       [5, 7, 8]])