In [3]:
import numpy as np

In [5]:
import numpy as np
#como hacer un rango con python puro
list(range(0,10))
#como hacer un rango con numpy
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [10]:
np.zeros((10,5))
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
#usando linspace -> que valor quiero que empiece, donde termina y cuantos datos quiero
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [12]:
#Crea una  matriz unitaria del orden que se ingrese el valor
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [13]:
#un valor aleatorio del 0 al 1
np.random.rand()

0.7866627359576636

In [14]:
#Primer parametro para la fila o 4 randoms (1x4)
np.random.rand(4)

array([0.48740887, 0.07907232, 0.59429343, 0.52714839])

In [16]:
#Una matriz de 3x3 de puro random
np.random.rand(3,3)

array([[0.97187148, 0.83162658, 0.20595887],
       [0.08025312, 0.04932933, 0.80886198],
       [0.70415104, 0.08870156, 0.33229005]])

In [18]:
#un random entre ... 
np.random.randint(1,100,(4,2))

array([[46, 12],
       [49, 12],
       [42, 78],
       [25, 63]])