Un escalar consta de una dim=0
Un vector consta de una dim=1
Una matriz consta de una dim=2 
Un tensor consta de una dim=n -> Ejemplo el manejo de imagenes (ancho,alto,canales y ejemplos)

In [1]:
import numpy as np


In [2]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [3]:
vector = np.array([1,2,3])
print(vector)
vector.ndim
#imprime

[1 2 3]


1

In [6]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)
matrix.ndim
#imprime

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2

In [10]:
tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]])
print(tensor)
tensor.ndim
#imprime

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


3

Agregar o elimitar dimensiones 

In [13]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim
#imprime

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [14]:
expand = np.expand_dims(np.array([1,2,3]), axis = 0)
print(expand)
expand.ndim
#imprime

[[1 2 3]]


2

In [16]:
print(vector, vector.ndim)
#Aqui, la dimension del vector es de 10, se declaró atras
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


Creando un tensor = 5
Agregando una dimensión al tensor
Eliminiar 2 dimensiones

In [29]:
print('dimension de 5')
daniell = np.array([[1,2,3], [4,5,6]], ndmin=5)
print(daniell, daniell.ndim)
print('dimension de 6')
daniell_2 = np.expand_dims(daniell, axis=0)
print(daniell_2, daniell_2.ndim)
print('dimension de 2')
daniell_3 = np.squeeze(daniell)
print(daniell_3, daniell_3.ndim)

dimension de 5
[[[[[1 2 3]
    [4 5 6]]]]] 5
dimension de 6
[[[[[[1 2 3]
     [4 5 6]]]]]] 6
dimension de 2
[[1 2 3]
 [4 5 6]] 2
