In [2]:
import numpy as np

In [4]:
arr = np.random.randint(1,20,10)

In [5]:
matrix = arr.reshape(2,5)
matrix

array([[11, 17, 14,  8, 19],
       [10, 16, 12, 15, 13]])

In [11]:
#Se puede aplicar tanto a renglones (0), como columnas (1)
matrix.max(0)


array([13, 15, 18,  7, 16])

In [12]:
#Esto devuelve la posicion del mas alto y el de menor indice (si hay varios)
matrix.argmax()

2

In [18]:
#Lo mismo, pero ahora con el valor mas pequeño
matrix.argmax(1)

array([2, 2])

In [19]:
#de un pico a otro pico ->
arr.ptp()

15

In [22]:
#Tema estadistico pa encontrar la media
np.percentile(arr,50)

12.0

In [23]:
arr

array([ 3, 15, 18,  3, 16, 13,  3, 18,  7, 11])

In [26]:
#Ordena los datos de menor a moyor
arr.sort()
arr

array([ 3,  3,  3,  7, 11, 13, 15, 16, 18, 18])

In [27]:
#Esto es con la mediana y aplica igual para las matrices
np.median(arr)

12.0

In [28]:
#La mediana aplicada al renglon 0
np.median(matrix,0)

array([ 8. ,  9. ,  9.5, 12.5, 14.5])

In [6]:
#para calcular la desviacion estandar
np.std(arr)

3.2015621187164243

In [7]:
#para calcular la varianza
np.var(arr)

10.25

In [8]:
#La media aplicada 
np.mean(arr)

13.5

In [22]:
#Concatenar -> se debe de asegurar que tengan la misma dimension
a = np.array([[1,2],[3,4]])
b = np.array([5,6])


In [23]:
b = np.expand_dims(b,axis=0)
np.concatenate((a,b),axis=0) 

array([[1, 2],
       [3, 4],
       [5, 6]])

In [24]:
#Para transponer -> cambiar renglon por columnas
b.T

array([[5],
       [6]])